# ===================================================================
# Spring Boot configuration for CI with H2 database (based on "dev" profile)
# ===================================================================

logging:
  level:
    ROOT: WARN
    tech.jhipster: INFO
    org.hibernate.SQL: DEBUG
    com.mycompany.myapp: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:dailyGratitudeJournal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false # not needed in CI
  liquibase:
    contexts: test
  mail:
    host: localhost
    port: 25
    username:
    password:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  cors:
    allowed-origin-patterns: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: YTg3YzdjZjUxZTYyOTI1MzcwNDQyNWFlMTg5Y2Q5NTdjMDBlOGVjYTAxNjY0YWE2MjEwMDVjNjc4NmViNzFhOGEzNmY3NzZlYzkyN2RkMjRhOTdkNjIzOTRlOTY5NGE0ZjUxODY2Y2NkYWQ1YjA0OWZiYTA0Y2E5NzYzZjgxNTA=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

# You may define additional test-specific properties below:
application:
  # Add app-specific props here
