package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GratitudeEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGratitudeEntryAllPropertiesEquals(GratitudeEntry expected, GratitudeEntry actual) {
        assertGratitudeEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertGratitudeEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGratitudeEntryAllUpdatablePropertiesEquals(GratitudeEntry expected, GratitudeEntry actual) {
        assertGratitudeEntryUpdatableFieldsEquals(expected, actual);
        assertGratitudeEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGratitudeEntryAutoGeneratedPropertiesEquals(GratitudeEntry expected, GratitudeEntry actual) {
        assertThat(actual)
            .as("Verify GratitudeEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGratitudeEntryUpdatableFieldsEquals(GratitudeEntry expected, GratitudeEntry actual) {
        assertThat(actual)
            .as("Verify GratitudeEntry relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getEntry()).as("check entry").isEqualTo(expected.getEntry()))
            .satisfies(a -> assertThat(a.getMood()).as("check mood").isEqualTo(expected.getMood()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGratitudeEntryUpdatableRelationshipsEquals(GratitudeEntry expected, GratitudeEntry actual) {
        // empty method
    }
}
